---
title: "Reading data"
output: github_document
---

```{r setup}
library(tidyverse)
library(rvest)
library(httr)

# add all the other plot options
```

## Script a table

First, we want the first table from the web. 
read in the HTML
```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm" # save the url to the variable called url
drug_use_html = read_html(url)

drug_use_html
```

extract the table(s); focus on the first one
```{r}
tabl_marj = 
  drug_use_html %>% 
  html_nodes(css = "table") %>% ## transfer the original data into table; 15 tables in total
  first() %>%  # take the first one; also there is end() or other similar functions
  html_table() %>% 
  slice(-1) %>% 
  as_tibble()
```

## CSS Selector: star wars movie info

get info from the web.

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = 
  read_html("https://www.imdb.com/list/ls070150896/")
```

grab elements that we need:
```{r}
title_vector =
  swm_html %>% 
  html_nodes(css = ".lister-item-header a") %>% 
  html_text()

gross_rev_vec =
  swm_html %>% 
  html_nodes(css = ".text-small:nth-child(7) span:nth-child(5)") %>% 
  html_text()

runtime_vec = 
  swm_html %>% 
  html_nodes(css = ".runtime") %>% 
  html_text()

swm_df = 
  tibble(
    title = title_vector,
    rev = gross_rev_vec,
    runtime = runtime_vec)
```

## APIs

Get some water data
```{r}
nyc_water = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed") # a function in httr package

nyc_water_json = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.json") %>% 
  content("text") %>% 
  jsonlite::fromJSON() %>% 
  as_tibble()
```

## BREFSS dataset

same process, different data
```{r}
brfss_smart2010 = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% # to request a query that is a list with the query parameter of 5000 $limit
  content("parsed")
```

## some data aren't so nice
Let's look at Pokemon

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

poke$name
poke$height
poke$abilities
```

## Closing thoughts

